#!/bin/bash
#
# IBM Cloud Private
#
# Author : Service Mesh Istio Authors
#
# Purpose: Prepare gluster peer domain 

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

NODES=(192.168.142.101 192.168.142.102 192.168.142.103)

echo ===================================================================
echo Enable and start glusterd service on all nodes
for ((i = 0; i < ${#NODES[@]}; ++i));
do
  host=${NODES[i]}
  echo Running on $host "$@"
  ssh $host systemctl enable glusterd
  ssh $host systemctl start glusterd
done

echo ===================================================================
gluster peer probe 192.168.142.102
gluster peer probe 192.168.142.103
echo ===================================================================
