#!/bin/bash
#
# IBM Cloud Private
#
# Author : Service Mesh Istio Authors
#
# Purpose: Create PV using Gluster

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo =================================================================================
echo Create PV and PVC

NS=ms

cat << EOF | kubectl -n $NS apply -f -
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-cdb-pv-1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  glusterfs:
    endpoints: glusterfs-endpoint
    path: /LV2G-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-cdb-pv-2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  glusterfs:
    endpoints: glusterfs-endpoint
    path: /LV2G-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-cdb-pv-3
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  glusterfs:
    endpoints: glusterfs-endpoint
    path: /LV2G-3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-web-pv-1
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  glusterfs:
    endpoints: glusterfs-endpoint
    path: /LV4G-1
---
EOF
