#!/bin/bash
#
# IBM Cloud Private 
#
# Author : Service Mesh Istio Book
#

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

read -p "Are you sure to uninstall? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Nn]$ ]]
then
   exit 1
fi

ICP_HOMEDIR=/opt/ibm/icp3.1.0

echo ========================================================
echo Uninstall the IBM Cloud Private environment
echo ========================================================
cd $ICP_HOMEDIR/cluster
docker run --rm \
   --net=host -t \
   -e LICENSE=accept \
   -v $(pwd):/installer/cluster \
   ibmcom/icp-inception:3.1.0 \
   uninstall -vv
