#!/bin/bash
#
# IBM Cloud Private 
#
# Author : Service Mesh Istio Book
#

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo ==============================================================
echo Checking if image is already loaded.
if docker images | grep -qs ibmcom/icp-inception; then 
   echo Image is already loaded. Exiting...
   echo ==============================================================
   exit 1
fi

echo ==============================================================
echo Pull docker image
echo ==============================================================

docker login
docker pull ibmcom/icp-inception:3.1.0
