#!/bin/bash
#
# IBM Cloud Private
#
# Author : Service Mesh Istio Book
#

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo ========================================================
echo Install IBM Cloud Private
echo ========================================================

cd /opt/ibm/icp3.1.0/cluster
docker run --rm \
   --net=host -t \
   --name=inception \
   -e LICENSE=accept \
   -e ANSIBLE_REMOTE_TEMP=/temp \
   -v $(pwd):/installer/cluster \
   ibmcom/icp-inception:3.1.0 \
   install -vv 
