#!/bin/bash
#
#
# Author : Author : Service Mesh Istio Book Authors
#
# Purpose: Sync clock and check the time difference

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

DIFF=${1:-400}
SSH="/bin/ssh -q -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no"
PS_LEADER=node01

function checkntp
{
  host=$1
  $SSH $host "vmware-toolbox-cmd timesync disable" 2>&1 > /dev/null
  try=0
  until [ $try -gt 5 ] ; do
    UP=$($SSH $host systemctl is-active --quiet ntpd && echo up || echo down)
    if [ "$UP" == "up" ] ; then
      break;
    else
      $SSH $host "systemctl is-active --quiet ntpd || systemctl start ntpd"
      sleep 1
    fi
    try=$[$try+1]
  done
}

function checktimediff
{
  host=$1
  try=0
  echo -n "Checking time diff between $host with the node01 .... "
  until [ $try -gt 5 ] ; do
     TIMEDIFF=$(ssh $host "ntpq -p | grep $PS_LEADER" | awk '{print $9}')
     if [ "$TIMEDIFF" == "" ] ; then
        echo Unable to get the time diff from $host
        break
     else
        N_TIMEDIFF=$(echo $TIMEDIFF | awk '{printf("%.0f\n", $1)}')
        N_TIMEDIFF=${N_TIMEDIFF#-}
        if [ $N_TIMEDIFF -gt $DIFF ] ; then
           echo Try=$try Resync time since time diff is $TIMEDIFF
           ssh $host "systemctl stop ntpd;ntpdate -b node01;systemctl start ntpd"
        else
           echo $TIMEDIFF milliseconds
           break
        fi
     fi
     try=$[$try+1]
  done
}


echo =================================================================================
checkntp node01
hosts="node02 node03"
for host in $hosts
do
   checkntp $host
   checktimediff $host
done
echo =================================================================================
